Misc lint

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -179,10 +179,17 @@ jobs:
             exit 1
           fi
       - name: "Misc lint"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/licence-headers-check', inputs.plugin-key)) != '' && hashFiles(format('{0}/tools/HEADER', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/tools/HEADER', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting licence headers checks...\033[0m"
-          vendor/bin/licence-headers-check --ansi --no-interaction
+          if [[ -f "vendor/bin/licence-headers-check" ]]; then
+            vendor/bin/licence-headers-check --ansi --no-interaction
+          elif [[ -f "../../vendor/bin/licence-headers-check" ]]; then
+            ../../vendor/bin/licence-headers-check --ansi --no-interaction --header-file=tools/HEADER -d .
+          else
+            echo -e "\033[0;31mLicence headers check binary not found!\033[0m"
+            exit 1
+          fi
       - name: "Install plugin"
         if: ${{ !cancelled() }}
         working-directory: "/var/www/glpi"
