PHP Parallel Lint

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -96,10 +96,16 @@ jobs:
         run: |
           npm install --no-save
       - name: "PHP Parallel Lint"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/parallel-lint', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting PHP Parallel Lint...\033[0m"
-          vendor/bin/parallel-lint --colors --exclude ./lib/ --exclude ./node_modules/ --exclude ./vendor/ --no-progress .
+          if [[ -f "vendor/bin/parallel-lint" ]]; then
+            vendor/bin/parallel-lint --colors --exclude ./lib/ --exclude ./node_modules/ --exclude ./vendor/ --no-progress .
+          elif [[ -f "../../vendor/bin/parallel-lint" ]]; then
+            ../../vendor/bin/parallel-lint --colors --exclude ./lib/ --exclude ./node_modules/ --exclude ./vendor/ --no-progress .
+          else
+            echo -e "\033[0;31mPHP Parallel Lint binary not found!\033[0m"
+            exit 1
+          fi
       - name: "PHP CodeSniffer"
         if: ${{ !cancelled() && hashFiles(format('{0}/.phpcs.xml', inputs.plugin-key)) != '' }}
         run: |
